### ISSUE TITLE
bad state from invalid accept()

### ISSUE THREAD

**Issue by 9001** [9001/r0c#1]
```
165108 client join:  bjkzhx  121.152.154.204  58021
165108      is bot:  bjkzhx  121.152.154.204
165142 client part:  bjkzhx  121.152.154.204  58021
165143 client join:  bjkzhx  121.152.154.204  58230
165143      is bot:  bjkzhx  121.152.154.204
165219 client part:  bjkzhx  121.152.154.204  58230
165220 client join:  bjkzhx  121.152.154.204  58467
165220      is bot:  bjkzhx  121.152.154.204
165254 client part:  bjkzhx  121.152.154.204  58467
165255 client join:  bjkzhx  121.152.154.204  58675
165256      is bot:  bjkzhx  121.152.154.204
165330 client join:  bgfvpt  121.152.154.204  58842
165330      is bot:  bgfvpt  121.152.154.204
165404 client part:  bgfvpt  121.152.154.204  58842
165406     botkick:  bjkzhx  121.152.154.204
165556              __
165556    _      __/ /_  ____  ____  ____  _____
165556   | | /| / / __ \/ __ \/ __ \/ __ \/ ___/
165556   | |/ |/ / / / / /_/ / /_/ / /_/ (__  )
165556   |__/|__/_/ /_/\____/\____/ .___/____/
165556                           /_/
165556 Traceback (most recent call last):
165556   File "/usr/lib/python2.7/asyncore.py", line 83, in read
165556     obj.handle_read_event()
165556   File "/usr/lib/python2.7/asyncore.py", line 443, in handle_read_event
165556     self.handle_accept()
165556   File "r0c/ivt100.py", line 75, in handle_accept
165556     remote = self.gen_remote(socket, addr, user)
165556   File "r0c/itelnet.py", line 151, in gen_remote
165556     return TelnetClient(self, socket, addr, self.world, user)
165556   File "r0c/itelnet.py", line 158, in __init__
165556     VT100_Client.__init__(self, host, socket, address, world, user)
165556   File "r0c/ivt100.py", line 186, in __init__
165556     int(time.time()), *list(self.addr))
165556 TypeError: 'NoneType' object is not iterable
165556 ----------------------------------------------------------------</stack>
165556              __
165556    _      __/ /_  ____  ____  ____  _____
165556   | | /| / / __ \/ __ \/ __ \/ __ \/ ___/
165556   | |/ |/ / / / / /_/ / /_/ / /_/ (__  )
165556   |__/|__/_/ /_/\____/\____/ .___/____/
165556                           /_/
165556 Traceback (most recent call last):
165556   File "/home/ed/dev/r0c/r0c/__main__.py", line 164, in asyncore_worker
165556     asyncore.loop(timeout, count=0.5/timeout)
165556   File "/usr/lib/python2.7/asyncore.py", line 220, in loop
165556     poll_fun(timeout, map)
165556   File "/usr/lib/python2.7/asyncore.py", line 132, in poll
165556     is_w = obj.writable()
165556   File "r0c/ivt100.py", line 497, in writable
165556     self.backlog or
165556   File "/usr/lib/python2.7/asyncore.py", line 421, in __getattr__
165556     %(self.__class__.__name__, attr))
165556 AttributeError: TelnetClient instance has no attribute 'backlog'
165556 ----------------------------------------------------------------</stack>
```
final exception refires ad infinitum

socket object turns None during the accept() sequence

might be due to client rapidly connecting and dropping

**Comment by 9001** [comment]
the plot thickens https://a.pomfe.co/rgdzlk.png
looks like socket.addr can turn None at any time
I don't like python
